// <auto-generated />
using System;
using Mentorship.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mentorship.Migrations
{
    [DbContext(typeof(MentorShipDbContext))]
    partial class MentorShipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mentorship.Models.Mentee", b =>
                {
                    b.Property<int>("MenteeId")
                        .HasColumnType("int")
                        .HasColumnName("mentee_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bio");

                    b.Property<string>("Interests")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("interests");

                    b.Property<string>("PreferredMentorAgeRange")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("preferred_mentor_age_range");

                    b.Property<string>("PreferredMentorGender")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("preferred_mentor_gender");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MenteeId")
                        .HasName("PK__Mentees__C079F297B66B7ADD");

                    b.HasIndex("UserId");

                    b.ToTable("Mentees");
                });

            modelBuilder.Entity("Mentorship.Models.Mentor", b =>
                {
                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<string>("AreaOfExpertise")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("area_of_expertise");

                    b.Property<string>("Availability")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("availability");

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bio");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("hourly_rate");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MentorId")
                        .HasName("PK__Mentors__E5D27EF3521379FF");

                    b.HasIndex("UserId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("Mentorship.Models.MentorshipSession", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int?>("MenteeId")
                        .HasColumnType("int")
                        .HasColumnName("mentee_id");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<string>("SessionNotes")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("session_notes");

                    b.Property<int?>("SessionRating")
                        .HasColumnType("int")
                        .HasColumnName("session_rating");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.HasKey("SessionId")
                        .HasName("PK__Mentorsh__69B13FDCEE44AE1E");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorshipSessions");
                });

            modelBuilder.Entity("Mentorship.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageContent")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message_content");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiver_id");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__0BBF6EE642E1AD51");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Mentorship.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.Property<int?>("MenteeId")
                        .HasColumnType("int")
                        .HasColumnName("mentee_id");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("review_date");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("review_text");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__60883D90458EA0C0");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Mentorship.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_picture");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registration_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370FF27E283D");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mentorship.Models.Mentee", b =>
                {
                    b.HasOne("Mentorship.Models.User", "User")
                        .WithMany("Mentees")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Mentees__user_id__29572725");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentorship.Models.Mentor", b =>
                {
                    b.HasOne("Mentorship.Models.User", "User")
                        .WithMany("Mentors")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Mentors__user_id__267ABA7A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentorship.Models.MentorshipSession", b =>
                {
                    b.HasOne("Mentorship.Models.Mentee", "Mentee")
                        .WithMany("MentorshipSessions")
                        .HasForeignKey("MenteeId")
                        .HasConstraintName("FK__Mentorshi__mente__2D27B809");

                    b.HasOne("Mentorship.Models.Mentor", "Mentor")
                        .WithMany("MentorshipSessions")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK__Mentorshi__mento__2C3393D0");

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Mentorship.Models.Message", b =>
                {
                    b.HasOne("Mentorship.Models.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Messages__receiv__30F848ED");

                    b.HasOne("Mentorship.Models.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Messages__sender__300424B4");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Mentorship.Models.Review", b =>
                {
                    b.HasOne("Mentorship.Models.Mentee", "Mentee")
                        .WithMany("Reviews")
                        .HasForeignKey("MenteeId")
                        .HasConstraintName("FK__Reviews__mentee___34C8D9D1");

                    b.HasOne("Mentorship.Models.Mentor", "Mentor")
                        .WithMany("Reviews")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK__Reviews__mentor___33D4B598");

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Mentorship.Models.Mentee", b =>
                {
                    b.Navigation("MentorshipSessions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Mentorship.Models.Mentor", b =>
                {
                    b.Navigation("MentorshipSessions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Mentorship.Models.User", b =>
                {
                    b.Navigation("Mentees");

                    b.Navigation("Mentors");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");
                });
#pragma warning restore 612, 618
        }
    }
}
